### ISSUE TITLE
fix vulnerability

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/cookie-url#4]
- Delete package-lock.json
- Run `npm install`
- Commit the updated package-lock.json
- Create pull request

**Comment by jugalj05hi** [comment]
Hi, I would like to take up this issue.

**Comment by arshadkazmi42** [comment]
go ahead. create a PR

**Comment by abhishek-bodapati** [comment]
If there isn't any progress, can I work on this?

**Comment by arshadkazmi42** [comment]
@abhishek-bodapati Go ahead. I don't think @jugalj05hi got a change to send a PR
